int cdFonction(char**, int);
int exitFonction(char**, int);
int nbBuiltins();
int nbLogicalsAndPipe();
int executeIfFirstSucceeds(char**, char**, int);
int readOrCreateFile(char*, char**, char**, int);
int pipeOperation(char**, char**, int);
int logicalOr(char**, char**, int);
int isInString(char*, char);
char** parseSentence(char*);
int execOperation(char**, int);
int analyseInstruction(char*, int);
int testMethod(char*, char*, char*, char*);
int getInstruction(char*, int, void*);
int readFromFile(int, char**, int, int, int, int);
int isSubstringHere(char*, char*, int);
int execute(char*, int);
