int cdFonction(char**);
int exitFonction(char**);
int nbBuiltins();
int stringLength(char*);
char** parseSentence(char*);
int execOperation(char**);
int analyseInstruction(char*);
char* getInstruction(char*);
void appendFile(char**, char**);
int readOrCreateFile(char*, char**, char**);
void pipeOperation(char**, char**);
void logicalAnd(char**, char**);
void logicalOr(char**, char**);
