int string_length(char*);
char** parseSentence(char*);
void execOperation(char**);
void analyseInstruction(char*, char*);
char* getInstruction(char*);
void appendFile(char* args);
void createFile(char*);
void readFromFile(char*);
void pipeOperation(char*);
void logicalAnd(char*);
void logicalOr(char*);
